### ISSUE TITLE
启动项目未能成功，『node index.js』运行之后没有出现任何提示

### ISSUE THREAD

**Issue by dwaynewei** [ruanyf/node-oauth-demo#2]
## 截图
* 
![image](https://user-images.githubusercontent.com/32864951/94224863-18e93c00-ff26-11ea-9e9d-cbf13918b60d.png)

## 问题描述
* 已经按照步骤操作，但运行node没有出现任何文字提示，请问这个是什么原因造成的？

**Comment by dwaynewei** [comment]
##  已解决
* 原来是因为我设置的GitHub授权页面中的地址 「localhost:8000」的8000端口实际上被占用了，所以打不开网页。  
* 修改为8080端口可以正常打开了。

**Comment by Clara-hy** [comment]
> ## 已解决
> * 原来是因为我设置的GitHub授权页面中的地址 「localhost:8000」的8000端口实际上被占用了，所以打不开网页。
> * 修改为8080端口可以正常打开了。

我用8080端口也打不开，没反应啊。还有没有其他的解决办法...
